kind: ConfigMap
apiVersion: v1
metadata:
  name: kafka-deterministic-consumer
data:
  application.properties: |-
    kafka.bootstrap.servers=strimzi-cluster-kafka-bootstrap.strimzi.svc:9092
    kafka.group.id=lag-consumer-test
    mp.messaging.incoming.requests.topic=test
    consumer.delay.ms=1000